name: Generate GitHub Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🧮 Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: JulienDesdo
          template: classic
          base: header, activity, community, repositories, languages
          config_timezone: Europe/Paris
          config_order: base.header, base.activity+community, base.repositories, languages, isocalendar, habits, topics
          config_display: large
          plugin_languages: yes
          plugin_languages_limit: 10
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_achievements: no
          plugin_repositories: no
          plugin_topics: yes
          plugin_topics_limit: 30
          plugin_topics_sort: stars
          plugin_topics_mode: icons
          plugin_topics_ignored: metrics
          plugin_topics_filter: curated
          plugin_topics_custom: |
            python, cpp, c, bash, powershell, javascript, r, matlab, tex,
            pytorch, scikit-learn, pandas, numpy, matplotlib, opencv,
            tensorflow, dataiku, docker, linux, git, github, vscode,
            aws, networks, cybersecurity, nmap, burpsuite, metasploit,
            tryhackme, machine-learning, deep-learning, signal-processing,
            ai, algorithms, cli, automation, devops, shell, datascience
          config_padding: 10%
          config_theme: default
