name: GitHub Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]  # mise à jour 2x/jour
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: JulienDesdo
          template: classic
          base: header, activity, repositories
          config_timezone: Europe/Paris

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: lines, percentage

          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: detailed
          plugin_achievements_secrets: no
          plugin_achievements_ignored: influencer, automator

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
